---
# tasks file for diskpart
- name: Install Partitioning Prerequisites
  apt:
    pkg: "{{ DISKPART_PACKAGES }}"
    state: present
    update_cache: yes

- name: Read Device {{ DISKPART_DEVICE }}
  parted:
    device: "{{ DISKPART_DEVICE }}"
    unit: "MiB"
  register: device_info
  when: DISKPART_DEVICE != None and DISKPART_DEVICE != ''

- name: Remove Partitions on Device {{ DISKPART_DEVICE }}
  parted:
    device: "{{ DISKPART_DEVICE }}"
    number: '{{ item.num }}'
    state: absent
  loop: '{{ device_info.partitions }}'
  when: DISKPART_DEVICE != None and DISKPART_DEVICE != ''

- name: Create Partitions on Device {{ DISKPART_DEVICE }}
  parted:
    device: "{{ item.disk }}"
    number: "{{ item.number }}"
    part_start: "{{ item.start }}"
    part_end: "{{ item.end }}"
    unit: "{{ item.unit }}"
    state: present
  with_items: "{{ DISKPART_DEVICE_PARTITIONS }}"

- name: Set Boot Flag on 1st Partition of Device {{ DISKPART_DEVICE }}
  parted:
    device: "{{ item.disk }}"
    number: "{{ item.number }}"
    part_start: "{{ item.start }}"
    part_end: "{{ item.end }}"
    unit: "{{ item.unit }}"
    state: present
  when: item.number == 1
  with_items: "{{ DISKPART_DEVICE_PARTITIONS }}"

- name: Set Boot Device
  set_fact:
    DISKPART_BOOT_DEVICE:
      device: "{{ DISKPART_DEVICE }}{{ item.number }}"
      fs: "ext2"
      path: "{{ DISKPART_CHROOT_DIR }}/boot"
  when: item.mountpoint == "/boot"
  with_items: "{{ DISKPART_DEVICE_PARTITIONS }}"

- name: Set Root Device
  set_fact:
    DISKPART_ROOT_DEVICE:
      device: "{{ DISKPART_DEVICE }}{{ item.number }}"
      fs: "ext4"
      path: "{{ DISKPART_CHROOT_DIR }}"
  when: item.mountpoint == "/"
  with_items: "{{ DISKPART_DEVICE_PARTITIONS }}"

- name: Format Partitions
  filesystem:
    dev: "{{ item.device }}"
    fstype: "{{ item.fs }}"
  with_items:
    - "{{ DISKPART_BOOT_DEVICE }}"
    - "{{ DISKPART_ROOT_DEVICE }}"

- name: Create boot Directory in {{ DISKPART_CHROOT_DIR }}
  file:
    path: "{{ DISKPART_CHROOT_DIR }}/boot"
    state: directory
    mode: 0755

- name: Mount Partitions
  mount:
    path: "{{ item.path }}"
    src: "{{ item.device }}"
    fstype: "{{ item.fs }}"
    boot: no
    state: mounted
  with_items:
    - "{{ DISKPART_ROOT_DEVICE }}"
    - "{{ DISKPART_BOOT_DEVICE }}"

- name: Get UUID for {{ DISKPART_BOOT_DEVICE.device }}
  shell: "blkid -s UUID -o value {{ DISKPART_BOOT_DEVICE.device }}"
  args:
    executable: "/bin/bash"
  register: diskpart_boot_dev_uuid

- name: Get UUID for {{ DISKPART_ROOT_DEVICE.device }}
  shell: "blkid -s UUID -o value {{ DISKPART_ROOT_DEVICE.device }}"
  args:
    executable: "/bin/bash"
  register: diskpart_root_dev_uuid
